stages:
  load_datassss:
    cmd: python stage_01_load_save.py --config=config/config.yaml
    deps:
      - stage_01_load_save.py
      - src/utils/all_utils.py
      - config/config.yaml 
    outs:
      - artifacts/raw_local_dir/data.csv