stages:
  load_data:
    cmd: python stage_01_load_save.py --config=config/config.yaml
    deps:
      - src/stage_01_load_save.py
      - src/utils/all_utils.py
      - config/config.yaml 
    outs:
      - artifacts/raw_local_dir/data.csv
  split_data:
    cmd: python stage_02_split_data.py --config=config/config.yaml --params=params.yaml
    deps: 
      - src/utils/all_utils.py
      - config/config.yaml
      - params.yaml
    params:
      - base.random_state
      - base.test_size
    outs:
    - artifacts/split_data_dir/test.csv
    - artifacts/split_data_dir/train.csv
  Train:
    cmd: python stage_03_train.py --config=config/config.yaml --params=params.yaml
    deps: 
      - stage_03_train.py
      - artifacts/split_data_dir/train.csv
      - src/utils/all_utils.py
      - config/config.yaml
      - params.yaml
    params:
      - base.random_state
      - model_params.ElasticNet.alpha
      - model_params.ElasticNet.l1_ratio


